# Generated by Django 3.1.7 on 2021-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'sale'), (2, 'new arrival'), (3, 'best seller')], null=True),
        ),
    ]
