# Generated by Django 3.1.7 on 2021-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'sale'), (2, 'new arrival'), (3, 'best seller')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
