# Generated by Django 3.1.7 on 2021-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Skirts'), (2, 'Panatlon'), (3, 'T-shirt'), (4, 'SweatShirt'), (5, 'pullover')], null=True),
        ),
    ]
